export const en = {
  settings: {
    label: "Settings",
    language: "Language",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    system: "System",
    english: "English",
    chinese: "中文",
  },
  common: {
    email: "Email",
    password: "Password",
    name: "Name",
    role: "Role",
    signIn: "Sign in",
    signOut: "Sign out",
    signingIn: "Signing in…",
    createAccount: "Create account",
    invalidInput: "Invalid input",
    signInFailed: "Sign in failed",
    signedIn: "Signed in",
    toggleSidebar: "Toggle sidebar",
    navigation: "Navigation",
  },
  web: {
    home: {
      title: "Web App",
      description:
        "A typical full-stack web application built with Next.js, React and a Go backend.",
      signIn: "Sign in",
      createAccount: "Create account",
    },
    login: {
      title: "Sign in",
      description: "Welcome back. Enter your credentials.",
      noAccount: "No account?",
      createOne: "Create one",
    },
    register: {
      title: "Create account",
      description: "Sign up to get started.",
      submit: "Create account",
      submitting: "Creating…",
      accountCreated: "Account created",
      registrationFailed: "Registration failed",
      haveAccount: "Already have an account?",
      signIn: "Sign in",
    },
    dashboard: {
      welcome: "Welcome, {{name}}",
      role: "Role: {{role}}",
      signOut: "Sign out",
    },
  },
  admin: {
    nav: {
      brand: "Web App Admin",
      users: "Users",
    },
    login: {
      title: "Admin sign in",
      description: "Restricted to administrators.",
      adminAccessRequired: "Admin access required",
    },
    users: {
      title: "Users",
      description: "Manage registered users and roles.",
      refresh: "Refresh",
      signOut: "Sign out",
      colName: "Name",
      colEmail: "Email",
      colRole: "Role",
      colCreated: "Created",
      colActions: "Actions",
      loading: "Loading…",
      empty: "No users found.",
      makeUser: "Make user",
      makeAdmin: "Make admin",
      updated: "Updated {{name}}",
      updateFailed: "Update failed",
      loadFailed: "Failed to load users",
    },
  },
  doc: {
    nav: {
      brand: "Web App Docs",
      apiReference: "API Reference",
      databaseSchema: "Database Schema",
      schemaEr: "ER Diagram",
      schemaUsers: "Users",
      apiAuth: "Auth",
      apiUsers: "Users",
    },
    home: {
      title: "Web App Docs",
      description:
        "Reference documentation for the Web App backend. Browse the database schema and the HTTP API from the sidebar.",
      schemaCardTitle: "Database Schema",
      schemaCardDescription:
        "PostgreSQL tables migrated from the GORM models, including the ER diagram and the users table.",
      apiCardTitle: "API Reference",
      apiCardDescription:
        "HTTP endpoints exposed by the backend, grouped into auth and users.",
    },
    api: {
      title: "API Reference",
      description: "HTTP endpoints exposed by the Web App backend (base URL {{baseUrl}}).",
      groupAuth: "Auth",
      groupUsers: "Users",
      bodyLabel: "Body",
      authBadge: "auth",
      registerSummary: "Create a new account and receive access & refresh tokens.",
      loginSummary: "Authenticate with credentials and receive tokens.",
      refreshSummary: "Exchange a refresh token for a new token pair.",
      meSummary: "Return the currently authenticated user.",
      listSummary: "List users (paginated). Admin only.",
      getSummary: "Fetch a single user by id. Admin only.",
      updateSummary: "Update a user's name or role. Admin only.",
    },
    schema: {
      title: "Database Schema",
      description:
        "PostgreSQL schema for the Web App backend, migrated automatically from the GORM models.",
      erTitle: "ER Diagram",
      erDescription:
        "The schema currently has a single users entity with no foreign-key relationships. New tables that reference users.id (e.g. sessions, posts) will appear here as related entities.",
      tableBadge: "table",
      colColumn: "Column",
      colType: "Type",
      colConstraints: "Constraints",
      colNotes: "Notes",
      indexesTitle: "Indexes",
      usersDescription:
        "Account records. Generated by GORM AutoMigrate from the User model. Uses soft deletes.",
      noteId: "Application-generated UUID",
      noteEmail: "Login identifier",
      noteName: "Display name (1–64 chars)",
      notePasswordHash: "bcrypt hash, never serialized",
      noteRole: "'user' | 'admin'",
      noteCreatedAt: "Set on insert",
      noteUpdatedAt: "Set on update",
      noteDeletedAt: "GORM soft delete marker",
    },
  },
} as const

/** Recursively widen literal string leaves to `string` for other locales. */
type Widen<T> = {
  [K in keyof T]: T[K] extends string ? string : Widen<T[K]>
}

export type Messages = Widen<typeof en>
